config/routes.rb
Rails.application.routes.draw do
  resources :comments  
  resources :filmes 
  resources :actors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "filmes#index"
end

app/models/actor.rb
class Actor < ApplicationRecord
    validates :name, :email, presence:true
    validates :birthyear, numericality: {only_integer: true, greater_than: 0, or_equal_to:2023 }
    has_and_belongs_to_many :filmes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  default scope :status, -> { where(:status => false)}
  validates :body, presence: true
  belongs_to :filme
end

app/models/filme.rb
class Filme < ApplicationRecord
    validates :title, :release_year, presence: true
    validates :release_year, numericality: {only_integer: true, greater_than: 0, or_equal_to:2022 } 

    has_and_belongs_to_many :actors
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: %i[ show edit update destroy ]

  # GET /actors or /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1 or /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors or /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to actor_url(@actor), notice: "Actor was successfully created." }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1 or /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to actor_url(@actor), notice: "Actor was successfully updated." }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1 or /actors/1.json
  def destroy
    @actor.destroy

    respond_to do |format|
      format.html { redirect_to actors_url, notice: "Actor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def actor_params
      params.require(:actor).permit(:name, :email, :birthyear)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :get_comment

  # GET /comments or /comments.json
  def index
    @filme = @filme.comments
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @filme.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = @filme.comment.build(filme_params)
    # @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to filme_comments_path(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to filme_comment_path(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to filme_comments_path(@comment), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def get_comment
    @filme = Filme.find(params[:filme_id])
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = @filme.comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:status, :body, :filme_id)
    end
end

app/controllers/filmes_controller.rb
class FilmesController < ApplicationController
  before_action :set_filme, only: %i[ show edit update destroy ]
  before_action :set_actors, only: %i[ new show edit update]

  # GET /filmes or /filmes.json
  def index
    @filmes = Filme.all
  end

  # GET /filmes/1 or /filmes/1.json
  def show
  end

  # GET /filmes/new
  def new 
    @filme = Filme.new
  end

  # GET /filmes/1/edit
  def edit
  end

  # POST /filmes or /filmes.json
  def create
    @filme = Filme.new(filme_params)

    respond_to do |format|
      if @filme.save
        format.html { redirect_to filme_url(@filme), notice: "Filme was successfully created." }
        format.json { render :show, status: :created, location: @filme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filmes/1 or /filmes/1.json
  def update
    respond_to do |format|
      if @filme.update(filme_params)
        format.html { redirect_to filme_url(@filme), notice: "Filme was successfully updated." }
        format.json { render :show, status: :ok, location: @filme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filmes/1 or /filmes/1.json
  def destroy
    @filme.destroy

    respond_to do |format|
      format.html { redirect_to filmes_url, notice: "Filme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  
  def set_actors
    @actors=Actor.all.pluck(:name, :id)
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_filme
      @filme = Filme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def filme_params
      params.require(:filme).permit(:title, :release_year)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/filmes_helper.rb
module FilmesHelper
end

app/views/actors/_actor.html.erb
<div id="<%= dom_id actor %>">
  <p>
    <strong>Name:</strong>
    <%= actor.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= actor.email %>
  </p>

  <p>
    <strong>Birthyear:</strong>
    <%= actor.birthyear %>
  </p>

</div>

app/views/actors/_form.html.erb
<%= form_with(model: actor) do |form| %>
  <% if actor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
        <% actor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :birthyear, style: "display: block" %>
    <%= form.number_field :birthyear %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing actor</h1>

<%= render "form", actor: @actor %>

<br>

<div>
  <%= link_to "Show this actor", @actor %> |
  <%= link_to "Back to actors", actors_path %>
</div>

app/views/actors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Actors</h1>

<div id="actors">
  <% @actors.each do |actor| %>
    <%= render actor %>
    <p>
      <%= link_to "Show this actor", actor %>
    </p>
  <% end %>
</div>

<%= link_to "New actor", new_actor_path %>

app/views/actors/new.html.erb
<h1>New actor</h1>

<%= render "form", actor: @actor %>

<br>

<div>
  <%= link_to "Back to actors", actors_path %>
</div>

app/views/actors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @actor %>

<div>
  <%= link_to "Edit this actor", edit_actor_path(@actor) %> |
  <%= link_to "Back to actors", actors_path %>

  <%= button_to "Destroy this actor", @actor, method: :delete %>
</div>

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Status:</strong>
    <%= comment.status %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= comment.body %>
  </p>

  <p>
    <strong>Filme:</strong>
    <%= comment.filme_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.check_box :status %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :filme_id, style: "display: block" %>
    <%= form.text_field :filme_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/filmes/_filme.html.erb
<div id="<%= dom_id filme %>">
  <p>
    <strong>Title:</strong>
    <%= filme.title %>
  </p>

  <p>
    <strong>Release year:</strong>
    <%= filme.release_year %>
  </p>

</div>

app/views/filmes/_form.html.erb
<%= form_with(model: [@filme, comment], local: true) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :release_year, style: "display: block" %>
    <%= form.number_field :release_year %>
  </div>

  <div>
    <%= form.label :actors_id , style: "display: block" %>
    <%= form.select :actors_id, @actors, {}, {} %>
  </div>

  <div class = "Write here:">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/filmes/edit.html.erb
<h1>Editing filme</h1>

<%= render "form", filme: @filme %>

<br>

<div>
  <%= link_to "Show this filme", @filme %> |
  <%= link_to "Back to filmes", filmes_path %>
</div>

app/views/filmes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Filmes</h1>

<div id="filmes">
  <% @filmes.each do |filme| %>
    <%= render filme %>
    <p>
    <%# <tbody>
      <% @filmes.each do |post| %>
        <%# <tr> %>
          <%# <td><%= comment.body %></td>
          <%# <td><%= comment.body.title %></td> %>
          <%# <td><%= link_to "Show this filme", [@filme] %></td> 

      <%= link_to "Show this filme", filme %>
    </p>
  <% end %>
</div>

<%= link_to "New filme", new_filme_path %>

app/views/filmes/new.html.erb
<h1>New filme</h1>

<%= render "form", filme: @filme %>

<br>

<div>
  <%= link_to "Back to filmes", filmes_path %>
</div>

app/views/filmes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @filme %>

<div>
  <%= link_to "Edit this filme", edit_filme_path(@filme) %> |
  <%= link_to "Back to filmes", filmes_path %>
 
  <%= button_to "Destroy this filme", @filme, method: :delete %>
</div>

app/views/layouts/_menu.html.erb
<a href= "/filmes">Filmes</a>
<a href= "/actor">Actor</a>
<a href= "/Comments">Comments</a>

<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IMDB</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/menu' %>
    <%= yield %>
  </body>
</html>